### ISSUE TITLE
Command 'Execute GraphQL Operations' resulted in an error (Cannot read property 'uri' of undefined)

### ISSUE THREAD

**Issue by cankahya** [graphql/vscode-graphql#269]
## Actual Behavior
Executing Query from VS Code doesn't show any results and throws error: 
"Command 'Execute GraphQL Operations' resulted in an error (Cannot read property 'uri' of undefined)"

## Expected Behavior
Should show Query result

## Steps to Reproduce the Problem Or Description
1. Install vscode-graphql
2. add 'graphql.config.js' to project root
3. add following content to graphql.config.js

`
const { projectConfig } = require('./project.config.js')

module.exports = {
  schema: './graphql/schema/_schema.graphql',
  documents: [':./graphql/queries/*.js'],
  extensions: {
    endpoints: {
      default: {
        url: projectConfig.apiUrl,
      },
    },
  },
}
`
assuming projectConfig.apiUrl is set to a string represantion of a valid graphql endpoint.

4. Open any Query.js file in ~/graphql/queries/ .
5. Click "Execute Query" as context option OR open command pallette and enter "Execute GraphQL Operations"

## Specifications

  - GraphQL for VSCode Extension Version: v0.3.13
  - VSCode Version: 1.52.1
  - OS Name: macOS Big Sur
  - OS Version: 11.1

**Comment by jdim** [comment]
Caught the same on Ubuntu inside Windows 10 WSL2

**Comment by sqren** [comment]
Running into this too. Logs:

```
[2021-12-16 20:07:05.798] [exthost] [error] TypeError: Cannot read property 'uri' of undefined
	at new JS (/Users/sqren/.vscode/extensions/graphql.vscode-graphql-0.3.50/out/extension.js:623:897)
	at /Users/sqren/.vscode/extensions/graphql.vscode-graphql-0.3.50/out/extension.js:624:3166
	at Generator.next (<anonymous>)
	at /Users/sqren/.vscode/extensions/graphql.vscode-graphql-0.3.50/out/extension.js:1:1305
	at new Promise (<anonymous>)
	at pr (/Users/sqren/.vscode/extensions/graphql.vscode-graphql-0.3.50/out/extension.js:1:1125)
	at /Users/sqren/.vscode/extensions/graphql.vscode-graphql-0.3.50/out/extension.js:624:2976
```

Config:
```js
module.exports = {
  schema: 'github-schema.graphql',
  extensions: {
    endpoints: {
      'GitHub API V4': {
        url: 'https://api.github.com/graphql',
        headers: {
          Authorization: `token ${accessToken}`,
          'user-agent': 'JS GraphQL',
        },
      },
    },
  },
};

```

**Comment by tepene** [comment]
Having the same issue:

![image](https://user-images.githubusercontent.com/54766327/147267379-850ec4c6-77e1-49ee-a867-a91763b43fc2.png)

## Steps to Reproduce the Problem Or Description

1. install vscode-graphql
2. add .graphqlrc.yaml to project root
3. add following content to .graphqlrc.yaml

```yaml
schema:
  - http://172.17.0.1:8080/v1/graphql:
      headers:
        x-hasura-admin-secret: "password"
extension:
  endpoints:
    default:
      url: http://172.17.0.1:8080/v1/graphql
      headers:
        x-hasura-admin-secret: "password"
```
4. Open any Query file
5. Open command palette and enter "Execute GraphQL Operations"

## Specifications

- GraphQL for VSCode Extension Version: v0.3.41
- VSCode Version: 1.63.2
- OS: Debian Buster (VSCode devcontainer)

**Comment by egoward** [comment]
Anyone got a workaround for this?

The language server is great, but it would be really helpful if I could run my graphql queries directly from vscode.

**Comment by sqren** [comment]
I'm now able to execute graphql queries directly in vscode against Github's api using this:

https://github.com/sqren/backport/blob/fb918690a5901b086b16880689f9f407f3988d62/.graphqlrc.js

**Comment by acao** [comment]
awesome yes, this is the way based on our readme!

you can also just require dotenv in the file and use .env variables in a local environment:


```ts
// graphql.config.ts
import { config } from 'dotenv'

// load .env config to process.env
config()

module.exports = {
  schema: 'https://api.github.com/graphql/',
  extensions: {
    endpoints: {
      default: {
        url: 'https://api.github.com/graphql',
        headers: {
          Authorization: `token ${process.env.accessToken}`,
          'user-agent': 'JS GraphQL',
        },
      },
    },
  },
};
```
Also above, I show this is possible with a remote schema pointer as well, though the local file pointer in your example will be faster. Just wanted to show the simplest version

We can also add support for the new graphql-config@4, graphql mesh-style schema endpoint configurations as well when there is time.

**Comment by egoward** [comment]
Thanks for the pointers, both.  I am up and running with my own schema & server.  My problem was basically user error, and perhaps some broken typescript setup stopping me following the instructions in the readme.

Naming things is hard, but in a picture -
![HowToExecuteQuery](https://user-images.githubusercontent.com/15047078/153035084-74970b06-d9a9-4840-a3bc-a55cee983f02.png)

**Comment by tepene** [comment]
> ```ts
> // graphql.config.ts
> import { config } from 'dotenv'
> 
> // load .env config to process.env
> config()
> ```

@acao I'm trying to load dotenv according to your example but I get an error `Error: graphql operation failed SyntaxError: Cannot use import statement outside a module`. What am I missing?

**Comment by tepene** [comment]
> > ```ts
> > // graphql.config.ts
> > import { config } from 'dotenv'
> > 
> > // load .env config to process.env
> > config()
> > ```
> 
> @acao I'm trying to load dotenv according to your example but I get an error `Error: graphql operation failed SyntaxError: Cannot use import statement outside a module`. What am I missing?

After a good night of sleep and some more debugging I found the solution(s):

```js
// graphql.config.js
const path = require("path");
require("dotenv").config({ path: path.join(__dirname, ".env") });

process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;

module.exports = {
  schema: [
    {
      "https://hasura.docker.internal/v1/graphql": {
        headers: {
          "x-hasura-admin-secret": process.env.HASURA_ADMIN_SECRET,
        },
      },
    },
  ],
  extensions: {
    endpoints: {
      default: {
        url: "https://hasura.docker.internal/v1/graphql",
        headers: {
          "x-hasura-admin-secret": process.env.HASURA_ADMIN_SECRET,
        },
      },
    },
  },
};
```
In addition to the above configuration I also had to install `dotenv`. Might be obvious for others but not for me ;)

```sh
npm install -g dotenv
npm link dotenv
```
A big thank you to all of you, who contributed to this issue. :+1:

### References:
- https://github.com/graphql/vscode-graphql/pull/267
- https://github.com/graphql/vscode-graphql/issues/284
