### ISSUE TITLE
Unable to load schema from `gql` tag

### ISSUE THREAD

**Issue by alexturpin** [graphql/vscode-graphql#458]
## Actual Behavior

When I try to load my schema from a `gql` tag, the GraphQL language server crashes.

## Expected Behavior

The server should not crash.

## Steps to Reproduce the Problem Or Description

Two files , both in the root of my project:

.graphqlrc.yml
```
schema: ./schema.ts
```

schema.ts
```
import gql from "graphql-tag"

gql`
  type Query {
    me: User
  }

  type User {
    id: ID
    name: String
  }
`
```

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.53
  - VSCode Version: 1.6..0
  - OS Name: macOS Monterey
  - OS Version: 12.2.1
  - graphql config filename and format example: see above

## Logs Of TS Server || GraphQL Language Service

```
[Info  - 4:03:47 PM] The graphql server has stopped running
GraphQL LSP restarted
(node:54701) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `Electron --trace-warnings ...` to show where the warning was created)
3/31/2022, 4:03:48 PM [3] (pid: 54701) graphql-language-service-usage-logs: {"type":"usage","messageType":"initialize"}
/Users/alexturpin/.vscode/extensions/graphql.vscode-graphql-0.3.53/out/server/server.js:119874
        throw new Error(`
              ^

Error: 
      Unable to find any GraphQL type definitions for the following pointers:
        
          - ./schema.ts
          
    at prepareResult (/Users/alexturpin/.vscode/extensions/graphql.vscode-graphql-0.3.53/out/server/server.js:119874:15)
    at loadTypedefs (/Users/alexturpin/.vscode/extensions/graphql.vscode-graphql-0.3.53/out/server/server.js:119848:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.loadSchema (/Users/alexturpin/.vscode/extensions/graphql.vscode-graphql-0.3.53/out/server/server.js:119892:23)
    at async GraphQLCache.getSchema (/Users/alexturpin/.vscode/extensions/graphql.vscode-graphql-0.3.53/out/server/server.js:122642:22)
[Error - 4:03:48 PM] Connection to server got closed. Server will not be restarted.
[Info  - 4:03:48 PM] The graphql server has stopped running
```

Am I doing something wrong? graphql-code-generator can load that same schema fine, through the same GraphQL config file.

**Comment by jhimy-michel** [comment]
I am having the same issue.
