### ISSUE TITLE
Cannot load schema by specifying a graphql API endpoint in gql config

### ISSUE THREAD

**Issue by peteole** [graphql/vscode-graphql#459]
## Actual Behavior
The server crashes when using an API endpoint to specify the schema.

## Expected Behavior
The extension fetches the API schema from the endpoint via introspection
## Steps to Reproduce the Problem Or Description
create a graphql.config.yml with the following content:
```yaml
schema:
  - https://huddle.hsg.fs.tum.de/api/query
```
The endpoint itself works fine as you can see here: https://huddle.hsg.fs.tum.de/api
## Specifications

  - GraphQL for VSCode Extension Version: 0.3.53
  - VSCode Version: 1.66.0-1
  - OS Name: manjaro linux
  - OS Version: plasma 5.24

## Logs Of TS Server || GraphQL Language Service
```bash
GraphQL LSP restarted
(node:433184) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `code --trace-warnings ...` to show where the warning was created)
3/31/2022, 10:12:36 PM [3] (pid: 433184) graphql-language-service-usage-logs: {"type":"usage","messageType":"initialize"}
/home/olep/.vscode/extensions/graphql.vscode-graphql-0.3.52/out/server/server.js:96572
            if (socket[kParser].timeoutType !== TIMEOUT_IDLE) {
                                ^

TypeError: Cannot read properties of undefined (reading 'timeoutType')
    at _resume (/home/olep/.vscode/extensions/graphql.vscode-graphql-0.3.52/out/server/server.js:96572:33)
    at resume (/home/olep/.vscode/extensions/graphql.vscode-graphql-0.3.52/out/server/server.js:96542:7)
    at connect (/home/olep/.vscode/extensions/graphql.vscode-graphql-0.3.52/out/server/server.js:96531:7)
[Info  - 10:12:37 PM] Connection to server got closed. Server will restart.
[Info  - 10:12:37 PM] The graphql server has stopped running
[Info  - 10:12:37 PM] The graphql server has stopped running
```

**Comment by Jose4gg** [comment]
+1 here
