### ISSUE TITLE
Extension crashed on VSCode 1.66.0 (Reading 'timeoutType')

### ISSUE THREAD

**Issue by suppayami** [graphql/vscode-graphql#460]
## Actual Behavior
Open graphql file and extension automatically crashed.

## Expected Behavior
Extension should run normally and allow seeing stuffs on hovering fields.

## Steps to Reproduce the Problem Or Description
Open a project with Graphql config, open a .graphql file and hover on a field.

## Specifications

  - GraphQL for VSCode Extension Version: v0.3.53
  - VSCode Version: 1.66.0
  - OS Name: Windows 10 (WSL 2)
  - graphql config filename and format example: graphql.config.toml
schema = "http://0.0.0.0:6543/api/graphql/"
documents = "src/**/*.graphql"

## Logs Of TS Server || GraphQL Language Service
```Restarting GraphQL LSP
[Info  - 9:14:19 AM] The graphql server has stopped running
GraphQL LSP restarted
(node:21776) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
4/1/2022, 9:14:20 AM [3] (pid: 21776) graphql-language-service-usage-logs: {"type":"usage","messageType":"initialize"}
/home/yami/.vscode-server/extensions/graphql.vscode-graphql-0.3.53/out/server/server.js:96572
            if (socket[kParser].timeoutType !== TIMEOUT_IDLE) {
                                ^

TypeError: Cannot read properties of undefined (reading 'timeoutType')
    at _resume (/home/yami/.vscode-server/extensions/graphql.vscode-graphql-0.3.53/out/server/server.js:96572:33)
    at resume (/home/yami/.vscode-server/extensions/graphql.vscode-graphql-0.3.53/out/server/server.js:96542:7)
    at connect (/home/yami/.vscode-server/extensions/graphql.vscode-graphql-0.3.53/out/server/server.js:96531:7)
[Error - 9:14:20 AM] Connection to server got closed. Server will not be restarted.
[Info  - 9:14:20 AM] The graphql server has stopped running
```

**Comment by suppayami** [comment]
Duplicated from graphql/graphiql#2269
