### ISSUE TITLE
GraphQL language server fails to start due to `Cannot read properties of undefined (reading 'timeoutType')`

### ISSUE THREAD

**Issue by enisdenjo** [graphql/vscode-graphql#462]
`.graphqlrc.yml` in project's root:
```yaml
schema:
  - http://localhost:5008/graphql
```

GQL lang server output:
```
4/5/2022, 4:28:38 PM [3] (pid: 62056) graphql-language-service-usage-logs: {"type":"usage","messageType":"initialize"}
/Users/enisdenjo/.vscode/extensions/graphql.vscode-graphql-0.3.53/out/server/server.js:96572
            if (socket[kParser].timeoutType !== TIMEOUT_IDLE) {
                                ^

TypeError: Cannot read properties of undefined (reading 'timeoutType')
    at _resume (/Users/enisdenjo/.vscode/extensions/graphql.vscode-graphql-0.3.53/out/server/server.js:96572:33)
    at resume (/Users/enisdenjo/.vscode/extensions/graphql.vscode-graphql-0.3.53/out/server/server.js:96542:7)
    at connect (/Users/enisdenjo/.vscode/extensions/graphql.vscode-graphql-0.3.53/out/server/server.js:96531:7)
[Info  - 4:28:38 PM] Connection to server got closed. Server will restart.
[Info  - 4:28:38 PM] The graphql server has stopped running
```

- node@v16
- vscode-graphql@v0.3.53
- vscode@1.66.0

**Comment by VictorGaiva** [comment]
Duplicate https://github.com/graphql/graphiql/issues/2269
